import { createTool } from "@mastra/core/tools";
import type { IMastraLogger } from "@mastra/core/logger";
import { z } from "zod";
import { sendEmail, type SmtpMessage } from "../../utils/replitmail";

export const emailReportTool = createTool({
  id: "send-email-report",
  description: "Sends a formatted email report with GitHub trending repositories data",
  inputSchema: z.object({
    recipientEmail: z.string().email().describe("Email address to send the report to"),
    repositories: z.array(z.object({
      name: z.string(),
      fullName: z.string(),
      language: z.string().nullable(),
      description: z.string().nullable(),
      stars: z.number(),
      url: z.string()
    })).describe("Array of repository data to include in the report")
  }),
  outputSchema: z.object({
    success: z.boolean(),
    messageId: z.string(),
    accepted: z.array(z.string())
  }),
  execute: async ({ context: { recipientEmail, repositories }, mastra }) => {
    const logger = mastra?.getLogger();
    logger?.info('🔧 [EmailReportTool] Starting execution to send email report', { 
      recipientEmail, 
      repositoryCount: repositories.length 
    });
    
    try {
      logger?.info('📝 [EmailReportTool] Formatting email content...');
      
      // Format the email content
      const currentDate = new Date().toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
      
      const subject = `GitHub Trending Repositories Report - ${currentDate}`;
      
      // Create HTML content
      const htmlContent = `
        <h2>🔥 GitHub Trending Repositories - ${currentDate}</h2>
        <p>Here are the top ${repositories.length} trending GitHub repositories:</p>
        
        <div style="margin: 20px 0;">
          ${repositories.map((repo, index) => `
            <div style="border: 1px solid #e1e4e8; border-radius: 6px; padding: 16px; margin: 12px 0; background-color: #f6f8fa;">
              <h3 style="margin: 0 0 8px 0; color: #0366d6;">
                ${index + 1}. <a href="${repo.url}" style="color: #0366d6; text-decoration: none;">${repo.fullName}</a>
              </h3>
              <p style="margin: 4px 0; color: #586069;">
                <strong>Language:</strong> ${repo.language || 'Not specified'}
                <span style="margin-left: 16px;"><strong>⭐ Stars:</strong> ${repo.stars.toLocaleString()}</span>
              </p>
              ${repo.description ? `<p style="margin: 8px 0 0 0; color: #24292e;">${repo.description}</p>` : ''}
            </div>
          `).join('')}
        </div>
        
        <hr style="margin: 20px 0; border: none; border-top: 1px solid #e1e4e8;">
        <p style="color: #586069; font-size: 14px;">
          This report was automatically generated by your GitHub Trending Bot.<br>
          Report generated on ${currentDate}
        </p>
      `;
      
      // Create plain text content
      const textContent = `
GitHub Trending Repositories Report - ${currentDate}

Here are the top ${repositories.length} trending GitHub repositories:

${repositories.map((repo, index) => `
${index + 1}. ${repo.fullName}
   Language: ${repo.language || 'Not specified'}
   Stars: ${repo.stars.toLocaleString()}
   URL: ${repo.url}
   ${repo.description ? `Description: ${repo.description}` : ''}
`).join('\n')}

---
This report was automatically generated by your GitHub Trending Bot.
Report generated on ${currentDate}
      `;
      
      logger?.info('📝 [EmailReportTool] Sending email...');
      
      const emailResult = await sendEmail({
        to: recipientEmail,
        subject: subject,
        html: htmlContent,
        text: textContent,
      });
      
      logger?.info('✅ [EmailReportTool] Email sent successfully', { 
        messageId: emailResult.messageId,
        accepted: emailResult.accepted
      });
      
      return {
        success: true,
        messageId: emailResult.messageId,
        accepted: emailResult.accepted
      };
      
    } catch (error) {
      logger?.error('❌ [EmailReportTool] Error sending email report', { 
        error: error instanceof Error ? error.message : String(error) 
      });
      throw error;
    }
  },
});